spring.jpa.hibernate.ddl-auto=update

# Feed 0
newswire.feeds[0].url=https://feeds.bbci.co.uk/news/rss.xml
newswire.feeds[0].sourceName=BBC News
newswire.feeds[0].category=FINANCE

# Feed 1
newswire.feeds[1].url=https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
newswire.feeds[1].sourceName=NYTimes
newswire.feeds[1].category=POLITICS

# Feed 2
newswire.feeds[2].url=https://www.npr.org/rss/rss.php?id=1001
newswire.feeds[2].sourceName=NPR
newswire.feeds[2].category=TECHNOLOGY

newswire.refresh.enabled=true
newswire.refresh.fixedDelayMs=600000
newswire.refresh.initialDelayMs=10000
newswire.refresh.fetchLimit=200
newswire.maxItems=40
